### ISSUE TITLE
Why another form object?

### ISSUE THREAD

**Issue by mattheworiordan** [GCorbel/activeform-rails#3]
@GCorbel, I was pretty excited when I saw your form object the other day, so integrated at the earliest opportunity.   Thanks for contributing it to the community.  However, as you can see, I've hit a number of issues using it and have done what I can to help by submitting my two pull requests #2 and #1.

I have now gone home and started wondering if I made the right choice changing from our home grown object models to this gem simply because it's turned out to be a lot more work than I thought.  I then did a bit of searching too and came across https://github.com/apotonick/reform.

I'd like to know specifically what you were aiming to achieve with this Gem as opposed to simply using https://github.com/apotonick/reform?  I am happy to help contribute, but equally if there is a gem out there that already does the job well, I'd like to know why we shouldn't just use that.

**Comment by TylerRick** [comment]
> I do think it's a common pattern that should be solved, and I am probably going to try and solve it as a Gem as opposed to simply writing code that we use in our code base.

@mattheworiordan Did you by any chance ever finish/publish your solution for this? (the code that provides `sync_and_validate_with`)

I'm currently looking for/at form object libraries and re-evaluating which one to use, and I resonated with most of the ideas you shared so would be interested in seeing what you use these days (if anything)...

I'd like to move away from Reform and towards something that more directly reuses standard ActiveModel modules... like https://github.com/oozou/active_form/blob/master/lib/active_form/base.rb , for instance
