### ISSUE TITLE
Rails 4 support?

### ISSUE THREAD

**Issue by acaeti** [GCorbel/activeform-rails#4]
Any plans to update (if any such updates are even needed) for Rails 4?

**Comment by aaronchi** [comment]
Any chance you can release a new gem for this?

**Comment by GCorbel** [comment]
Is it working with the master branch ? If yes, I will release a new version soon.

**Comment by aaronchi** [comment]
Seems to be working, yes

**Comment by GCorbel** [comment]
I did it!
